### PR TITLE
added suport for isomorphic rendering

### PR DESCRIPTION
**Pull request by dinodsaurus**
I just added check if the component is running in browser or node.
Before when rendering on server there was an error 
```
/Users/dino/Documents/dino/react-modal/lib/helpers/ariaAppHider.js:4
if (document) {
    ^

ReferenceError: document is not defined
```

### CODE REVIEW

**Comment by tkirda** [comment]
Yes, that is needed! Now it fails when rendering isomorphic app. I suggest changing first line into:

```javascript
var _element = typeof document !== 'undefined' ? document.body : null;
```

There is no point setting _element to string.

**Comment by dinodsaurus** [comment]
Thanks for this, I updated my pull request :+1:

**Comment by Josh-a-e** [comment]
Would love to see this merged in :smile:

**Comment by sebslomski** [comment]
Please merge this, it works perfectly.

**Comment by ghislaindj** [comment]
Totally agree, this PR works great !

**Comment by voronianski** [comment]
rackt guys @gaearon @mzabriskie pleas merge this line and bump npm version pleeeeeaseee :watch:

**Comment by mzabriskie** [comment]
Has anyone tested this diff with a screen reader? The fix would work for server rendering. Just need to make sure that once we're on the client `_element` still gets `aria-hidden="true"` when modal is displayed.

**Comment by tkirda** [comment]
It does not affect the behavior in any way, it's just to prevent exception when including file in nodejs runtime. Since `document` is not available. On a client it will behave the same way.

**Comment by mzabriskie** [comment]
Sounds good. Thanks!

**Comment by tkirda** [comment]
Sweet! Looking forward to see it on NPM.

**Comment by voronianski** [comment]
@mzabriskie :+1:

**Comment by Spy-Seth** [comment]
Any idea on when a new release will be?

**Comment by mzabriskie** [comment]
I will update react to 0.14, and release today.

**Comment by sahat** [comment]
Has this been published yet? I am still having this issue in version 0.5.

**Comment by jhabdas** [comment]
+1

**Comment by vonwao** [comment]
Still doesn't work with meteor.

**Comment by ericntd** [comment]
It looks like the fix is included in 0.6.0.
But then 0.6.0 requires React 0.14 and I'm using React 0.13.3.
What else can I do besides crying and changing the source code of your library under node_modules folder?

**Comment by dinodsaurus** [comment]
In my `package.json`I am loading it as this:
`"react-modal": "git+https://github.com/rackt/react-modal.git#920d421ed14b94b47bb32310eb691f763d67d464"`

**Pull request merged**
