### PR TITLE
Fix peer dependency version for React in PR #68

### PR DESCRIPTION
**Pull request by 9o**
Fixes #68 #67 #77

0.14 was officially released a couple days ago so merging @rogeliog's changes would be great :)

### CODE REVIEW

**Comment by TaopaiC** [comment]
Hi @9o ,
  I think exenv is needed in dependencies. (or in peerDependencies ?)

**Comment by mzabriskie** [comment]
@9o PR looks good. Would you mind resolving conflicts, and I'll get it merged? Thanks!

**Comment by yashprit** [comment]
@9o Could you please resolve conflict, so that your pull can be merged, we are using react-modal and very soon wanted to move to react 0.14. Thanks

**Comment by 9o** [comment]
I'll try to fix the conflicts tonight :)

**Comment by jhabdas** [comment]
+1

**Comment by roth1002** [comment]
@9o 

we need it  :)

**Comment by jhabdas** [comment]
Sweet business. Thanks!

**Pull request closed without merging**
